services:
  app:
    build: .
    ports:
      - '8080:8080'
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/wallet
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    depends_on:
      - postgres

  postgres:
    image: 'postgres:14'
    environment:
      - POSTGRES_URL=jdbc:postgresql://localhost:5432/wallet
      - POSTGRES_DB=wallet
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=postgres
    ports:
      - '6542:5432'
